language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./reverseproxy

# Tagging
  - docker tag udagram-api-feed ifyncode/udagram-api-feed:v1
  - docker tag udagram-api-user ifyncode/udagram-api-user:v1
  - docker tag udagram-frontend ifyncode/udagram-frontend:v1
  - docker tag udagram-reverseproxy ifyncode/udagram-reverseproxy:v1
# Do similar for other three images

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker push ifyncode/udagram-api-feed:v1
  - docker push ifyncode/udagram-api-user:v1
  - docker push ifyncode/udagram-frontend:v1
  - docker push ifyncode/udagram-reverseproxy:v1


